[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_vesting = "6ZFtauozJcpn6fSYwispi9toTvsSKkS1GEPv7a77SSvo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/alizeeshan/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
